/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vqq2EkAzn3CTTzmF7cN3ao
// Component: 1yiwtfdP4kH3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HeaderNavBar from "../../HeaderNavBar"; // plasmic-import: 6Us2WCXn4WFf/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import ServiceCard from "../../ServiceCard"; // plasmic-import: WpsoIcLzp7L2/component
import ProcessCard from "../../ProcessCard"; // plasmic-import: Uah7VsWpV6Q4/component
import TeamsCard from "../../TeamsCard"; // plasmic-import: MlYa0Ac5yeND/component
import Button from "../../Button"; // plasmic-import: TUfunDceiXe8/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import TestimonialCard from "../../TestimonialCard"; // plasmic-import: Qey7pJzlldRh/component

import { useScreenVariants as useScreenVariantsbcqIyMmwg5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _bcqIYMmwg5_/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: vqq2EkAzn3CTTzmF7cN3ao/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 1yiwtfdP4kH3/css

import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: I1-UL0cTF0ke/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: gQ9GL9qi87FQ/icon
import ChevronDown2Icon from "./icons/PlasmicIcon__ChevronDown2"; // plasmic-import: qG4-swCrl7ga/icon
import InstagramSvgrepoComSvgIcon from "./icons/PlasmicIcon__InstagramSvgrepoComSvg"; // plasmic-import: aHoszmLT10rp/icon
import FacebookSvgrepoComSvgIcon from "./icons/PlasmicIcon__FacebookSvgrepoComSvg"; // plasmic-import: c73RtLfNBEOR/icon
import EmailSvgrepoComSvgIcon from "./icons/PlasmicIcon__EmailSvgrepoComSvg"; // plasmic-import: NnlUgWY9zufC/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  headerNavBar?: Flex__<typeof HeaderNavBar>;
  h1?: Flex__<"h1">;
  blockquote?: Flex__<"blockquote">;
  columns?: Flex__<"div">;
  sliderCarousel?: Flex__<typeof SliderWrapper>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbcqIyMmwg5()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <section className={classNames(projectcss.all, sty.section__h7So)}>
            <HeaderNavBar
              data-plasmic-name={"headerNavBar"}
              data-plasmic-override={overrides.headerNavBar}
              className={classNames("__wab_instance", sty.headerNavBar)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__bUueP)}>
              <div className={classNames(projectcss.all, sty.freeBox___9A39Q)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__qC98L)}
                  displayHeight={"auto"}
                  displayMaxHeight={"100%"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/hockey_lab_website/images/logoVerticalWhiteSvg.svg",
                    fullWidth: 233.84,
                    fullHeight: 371.63,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__bj20N)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__xouM)}
                    delay={500}
                    duration={2000}
                    triggerOnce={true}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"We develop \nhockey talents"}
                    </h1>
                  </Reveal>
                  <blockquote
                    data-plasmic-name={"blockquote"}
                    data-plasmic-override={overrides.blockquote}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.blockquote
                    )}
                  >
                    {
                      "Inspiring and empowering future field hockey generation through innovative coaching"
                    }
                  </blockquote>
                </div>
              </div>
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__zIcrF
              )}
              component={Link}
              href={`/#${"our-services"}`}
              onClick={async event => {
                const $steps = {};

                $steps["updateStateVariable"] = true
                  ? (() => {
                      const actionArgs = {};
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;
                        undefined;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateStateVariable"] != null &&
                  typeof $steps["updateStateVariable"] === "object" &&
                  typeof $steps["updateStateVariable"].then === "function"
                ) {
                  $steps["updateStateVariable"] = await $steps[
                    "updateStateVariable"
                  ];
                }
              }}
              onScroll={async event => {
                const $steps = {};

                $steps["updateStateVariable"] = true
                  ? (() => {
                      const actionArgs = {};
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;
                        undefined;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateStateVariable"] != null &&
                  typeof $steps["updateStateVariable"] === "object" &&
                  typeof $steps["updateStateVariable"].then === "function"
                ) {
                  $steps["updateStateVariable"] = await $steps[
                    "updateStateVariable"
                  ];
                }
              }}
              platform={"nextjs"}
            >
              <ChevronDownIcon
                className={classNames(projectcss.all, sty.svg__eW5Xw)}
                role={"img"}
              />
            </PlasmicLink__>
          </section>
          <section
            className={classNames(projectcss.all, sty.section__gywZl)}
            id={"our-services"}
          >
            <div className={classNames(projectcss.all, sty.freeBox___0USJz)}>
              <h6
                className={classNames(
                  projectcss.all,
                  projectcss.h6,
                  projectcss.__wab_text,
                  sty.h6__tMavv
                )}
              >
                {"Achieve your goals"}
              </h6>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__ed3Q
                )}
              >
                {"With our Coaching Services"}
              </h2>
            </div>
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__flh2)}>
                <ServiceCard
                  className={classNames(
                    "__wab_instance",
                    sty.serviceCard__fkoVy
                  )}
                  slot={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__t87L
                      )}
                    >
                      {"Club & School Coaching"}
                    </div>
                  }
                  slot3={
                    "Our approach centers on building a strong team bond and a supportive growth environment, enabling each player to reach their full potential while striving for shared success."
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__iIJq7)}>
                <ServiceCard
                  className={classNames(
                    "__wab_instance",
                    sty.serviceCard___9Swmi
                  )}
                  slot={"Individual & Group Coaching"}
                  slot2={
                    "Personalised training tailored for individual and small group needs"
                  }
                  slot3={
                    "Our individual and group training prioritize maximizing ball contact time and specificity to deliver optimal player development."
                  }
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___4Bq91)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"175px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/hockey_lab_website/images/fitnessPng.png",
                      fullWidth: 2000,
                      fullHeight: 2000,
                      aspectRatio: undefined
                    }}
                  />
                </ServiceCard>
              </div>
              <div className={classNames(projectcss.all, sty.column__h4DAc)}>
                <ServiceCard
                  className={classNames(
                    "__wab_instance",
                    sty.serviceCard__kt6N
                  )}
                  slot={"Hockey Tour"}
                  slot2={
                    "Experience foreign hockey culture with our overseas tour"
                  }
                  slot3={
                    "We take care of all the logistics \u2013 transportation, accommodation, training facilities, and opponent scheduling \u2013 so you can focus on your hockey."
                  }
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__stpHy)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"175px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/hockey_lab_website/images/travelingPng.png",
                      fullWidth: 2000,
                      fullHeight: 2000,
                      aspectRatio: undefined
                    }}
                  />
                </ServiceCard>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__v69Ep)}>
            <div className={classNames(projectcss.all, sty.freeBox__zwh3V)}>
              <h6
                className={classNames(
                  projectcss.all,
                  projectcss.h6,
                  projectcss.__wab_text,
                  sty.h6__q57YY
                )}
              >
                {"Embark on your field hockey journey"}
              </h6>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__xnJOe
                )}
              >
                {"Stages of Development"}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__zhVkW)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1D0G
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ textDecorationLine: "underline" }}
                  >
                    {"We understand field hockey players"}
                  </span>
                  <React.Fragment>
                    {
                      ", training is adapted to individual needs at every stage. Our coaches expertly craft engaging sessions using scientific principles, ensuring specificity, progressive overload, and maintaining motivation for athletes of all ages and abilities."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__wxRr)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__dVarP)}
                  delay={500}
                  duration={3000}
                  triggerOnce={true}
                >
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard___9THlV
                    )}
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pOeVm
                        )}
                      >
                        {"Age 2-5"}
                      </div>
                    }
                  >
                    {"Discover"}
                  </ProcessCard>
                </Reveal>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__udrjY)}
                  delay={1000}
                  duration={3000}
                  triggerOnce={true}
                >
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard__ueCe
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__csJaj
                        )}
                      >
                        {"2"}
                      </div>
                    }
                    slot2={"Age 6-10"}
                  />
                </Reveal>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__pZHrT)}
                  delay={2000}
                  duration={3000}
                  triggerOnce={true}
                >
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard__uLdnd
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gl9BA
                        )}
                      >
                        {"3"}
                      </div>
                    }
                    slot2={"Age 10-16"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aFb4H
                      )}
                    >
                      {"Compete & Improve"}
                    </div>
                  </ProcessCard>
                </Reveal>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__cPWy)}
                  delay={2500}
                  duration={3000}
                  triggerOnce={true}
                >
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard__ck7Q
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oq94N
                        )}
                      >
                        {"4"}
                      </div>
                    }
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zoTy0
                        )}
                      >
                        {"Age 16-40"}
                      </div>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lxfY
                      )}
                    >
                      {"Peak Performance"}
                    </div>
                  </ProcessCard>
                </Reveal>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__aO7T)}
                  delay={3000}
                  duration={3000}
                  triggerOnce={true}
                >
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard__xOyzs
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nNlBz
                        )}
                      >
                        {"5"}
                      </div>
                    }
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jrovG
                        )}
                      >
                        {"Age 40+"}
                      </div>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cTbs0
                      )}
                    >
                      {"Lifetime Engagement"}
                    </div>
                  </ProcessCard>
                </Reveal>
              </div>
            </div>
            <section className={classNames(projectcss.all, sty.section__odpkc)}>
              <div className={classNames(projectcss.all, sty.freeBox__mWiys)}>
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6___70Eqk
                  )}
                >
                  {"Guiding you along with our exceptional"}
                </h6>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___7Ty5C
                  )}
                >
                  {"Coaching Team"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iSenu
                  )}
                >
                  {"International Experience"}
                </div>
              </div>
            </section>
          </section>
          <section className={classNames(projectcss.all, sty.section__zdrLw)}>
            <div className={classNames(projectcss.all, sty.freeBox__ntHBt)}>
              <h6
                className={classNames(
                  projectcss.all,
                  projectcss.h6,
                  projectcss.__wab_text,
                  sty.h6__rd7K
                )}
              >
                {"Write your success story with us"}
              </h6>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__k73PE
                )}
              >
                {"Honor achieved by our teams & individuals"}
              </h2>
              <div className={classNames(projectcss.all, sty.freeBox__sv5O2)}>
                <div className={classNames(projectcss.all, sty.freeBox__t2NZc)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__hLwOo
                    )}
                  >
                    {"35+"}
                  </h3>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__u0Pso
                    )}
                  >
                    {"Schools & Teams"}
                  </h4>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__oEnPs)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__xoTyQ
                    )}
                  >
                    {"300+"}
                  </h3>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__iytX6
                    )}
                  >
                    {"Students"}
                  </h4>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6UO8N)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__fGaUl
                    )}
                  >
                    {"20+"}
                  </h3>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__xupUo
                    )}
                  >
                    {"Team & Individual Awards"}
                  </h4>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__sZm0E)}>
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__ps1K
                )}
              >
                {"Premier League Teams"}
              </h3>
              <div className={classNames(projectcss.all, sty.freeBox__qi8Hr)}>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__kd7O1)}
                  slot={"Men's & Women's Competition"}
                  slot2={"Antlers Hockey Club"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___4LFc3)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/anterlsLogoBlackSvg.svg",
                        fullWidth: 528.86,
                        fullHeight: 385.3,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button___3MEfa)}
                    color={"blue"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gx9Nx
                        )}
                      >
                        {"Premier League"}
                      </div>
                    }
                  />
                </TeamsCard>
                <TeamsCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamsCard___0O4U5
                  )}
                  slot={"Women's Competition"}
                  slot2={"Solis Hockey Club"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__hu7K7)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/solisLogoPng.png",
                        fullWidth: 1535,
                        fullHeight: 1535,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__d5Ieg)}
                    color={"blue"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aeGXr
                        )}
                      >
                        {"Premier League"}
                      </div>
                    }
                  />
                </TeamsCard>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__xM9Ke)}>
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__qDxRm
                )}
              >
                {"Development Teams"}
              </h3>
              <div className={classNames(projectcss.all, sty.freeBox__qL45S)}>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__fQd2S)}
                  slot={"HKSSF Interschool Competition"}
                  slot2={"Heep Yunn School"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__x2F0V)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/heepYunnSchoolLogoJpg.jpg",
                        fullWidth: 300,
                        fullHeight: 300,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__fp5Vv)}
                    color={"blue"}
                    disabled={false}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__na5TU
                        )}
                      >
                        {"Champion"}
                      </div>
                    }
                  />
                </TeamsCard>
                <TeamsCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamsCard___2Dmoe
                  )}
                  slot={"HKSSF Interschool Competition"}
                  slot2={"Diocesan Boys' School"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__diUhb)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/diocesanBoysSchoolLogoPng.png",
                        fullWidth: 60,
                        fullHeight: 73,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__uy8GI)}
                    color={"blue"}
                    disabled={false}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yvatK
                        )}
                      >
                        {"Champion"}
                      </div>
                    }
                  />
                </TeamsCard>
                <TeamsCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamsCard___0TnK6
                  )}
                  slot={"HKSSF Interschool Competition"}
                  slot2={"Sha Tin College"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qzg0Y)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/_4058885310941814707225365581507840230555648NJpg.jpg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__mt1Tg)}
                    color={"blue"}
                    disabled={false}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__biMxQ
                        )}
                      >
                        {"Champion"}
                      </div>
                    }
                  />
                </TeamsCard>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__lcPPa)}
                  slot={"HK Developmental Competition"}
                  slot2={"Tai Po Titans"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___6Vo3X)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/titansLogoJpg.jpg",
                        fullWidth: 1241,
                        fullHeight: 1241,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__xhqgA)}
                    color={"blue"}
                    disabled={false}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__akTnb
                        )}
                      >
                        {"Champion"}
                      </div>
                    }
                  />
                </TeamsCard>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__jfQpg)}
                  slot={"China National U12 Youth Competition"}
                  slot2={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xxFs
                      )}
                    >
                      {"Yucai Dengyun School"}
                    </div>
                  }
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__hxqnK)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/yuCaiLogoSvg.svg",
                        fullWidth: 756.48,
                        fullHeight: 756.48,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__o3If6)}
                    color={"blue"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___47G
                        )}
                      >
                        {"Runners Up"}
                      </div>
                    }
                  />
                </TeamsCard>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__lWt8)}>
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__iPkKr
                )}
              >
                {"HKU Hall Teams"}
              </h3>
              <div className={classNames(projectcss.all, sty.freeBox__apHx)}>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__qb2Wk)}
                  slot={"Men's Interhall Competition"}
                  slot2={"Swire Hall"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___8KTg7)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/diocesanBoysSchoolLogoPng.png",
                        fullWidth: 60,
                        fullHeight: 73,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__wNpS7)}
                    color={"blue"}
                    disabled={false}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vofIh
                        )}
                      >
                        {"Champion"}
                      </div>
                    }
                  />
                </TeamsCard>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__oMYy)}
                  slot={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0YABf
                      )}
                    >
                      {"Men's & Women's Inter-Hall Competition"}
                    </div>
                  }
                  slot2={"Starr Hall"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___3KHly)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/starrHallLogoSvg.svg",
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__nv3E)}
                    color={"blue"}
                    disabled={false}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kzqTj
                        )}
                      >
                        {"Runners Up"}
                      </div>
                    }
                  />
                </TeamsCard>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__oItNx)}>
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__ueOyn
                )}
              >
                {"Individual Awards"}
              </h3>
              <div className={classNames(projectcss.all, sty.freeBox___91R2M)}>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__wxI97)}
                  slot={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s1WFe
                      )}
                    >
                      {"Player of the Tournament & Top Goal Scrorer"}
                    </div>
                  }
                  slot2={"HSIEH Tsung Yu"}
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__edIhV)}
                      displayHeight={"50px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/chinesTaipeiFlagPng.png",
                        fullWidth: 255,
                        fullHeight: 170,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__k6OWl)}
                    color={"blue"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lgTbM
                        )}
                      >
                        {"AHF Cup & HKG Quadrangular"}
                      </div>
                    }
                  />
                </TeamsCard>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__o4Xq)}
                  slot={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1EL9U
                      )}
                    >
                      {"Player of the Tournament"}
                    </div>
                  }
                  slot2={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vDjC3
                      )}
                    >
                      {"HUANG Yu Ting"}
                    </div>
                  }
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__hfy2C)}
                      displayHeight={"50px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/chinesTaipeiFlagPng.png",
                        fullWidth: 255,
                        fullHeight: 170,
                        aspectRatio: undefined
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__nmqze)}
                    color={"blue"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ccFzV
                        )}
                      >
                        {"Junior AHF Cup"}
                      </div>
                    }
                  />
                </TeamsCard>
                <TeamsCard
                  className={classNames("__wab_instance", sty.teamsCard__w7Up)}
                  slot={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__furMd
                      )}
                    >
                      {"Most Valuable Player"}
                    </div>
                  }
                  slot2={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hl53N
                      )}
                    >
                      {"IU Chi Him, Felix"}
                    </div>
                  }
                  slot3={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__cGq0N)}
                      displayHeight={"50px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hockey_lab_website/images/hkSvg.svg",
                        fullWidth: 640,
                        fullHeight: 480,
                        aspectRatio: 1.333333
                      }}
                    />
                  }
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__iwpwj)}
                    color={"blue"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bwLqP
                        )}
                      >
                        {"Melbourne Cup"}
                      </div>
                    }
                  />
                </TeamsCard>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___0B1Gr)}>
            <div className={classNames(projectcss.all, sty.freeBox__ylLw0)}>
              <h6
                className={classNames(
                  projectcss.all,
                  projectcss.h6,
                  projectcss.__wab_text,
                  sty.h6__raBeR
                )}
              >
                {"Customer Stories"}
              </h6>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__sIjP
                )}
              >
                {"Hear what they have to say"}
              </h2>
            </div>
            {(() => {
              const child$Props = {
                arrowColor: true ? "#D1D5DB" : undefined,
                arrows: hasVariant(globalVariants, "screen", "mobileOnly")
                  ? false
                  : true,
                autoplay: false,
                autoplaySpeed: 0,
                beforeChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "currentSlide",
                    ["sliderCarousel", "currentSlide"],
                    SliderWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                centerMode: true,
                className: classNames("__wab_instance", sty.sliderCarousel),
                cssEase: "linear",
                dots: true,
                initialSlide: generateStateValueProp($state, [
                  "sliderCarousel",
                  "currentSlide"
                ]),
                ref: ref => {
                  $refs["sliderCarousel"] = ref;
                },
                sliderScopeClassName: sty["sliderCarousel__slider"],
                speed: 500
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "currentSlide",
                    plasmicStateName: "sliderCarousel.currentSlide"
                  }
                ],
                [],
                SliderWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <SliderWrapper
                  data-plasmic-name={"sliderCarousel"}
                  data-plasmic-override={overrides.sliderCarousel}
                  {...child$Props}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eLp2H)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__coBlS)}
                    >
                      <TestimonialCard
                        className={classNames(
                          "__wab_instance",
                          sty.testimonialCard__sqsd0
                        )}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mhUcK)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___6IjJu
                      )}
                    >
                      <TestimonialCard
                        className={classNames(
                          "__wab_instance",
                          sty.testimonialCard__ezBko
                        )}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___2PW1S)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__njJ1M)}
                    >
                      <TestimonialCard
                        className={classNames(
                          "__wab_instance",
                          sty.testimonialCard__wHCrh
                        )}
                      />
                    </div>
                  </div>
                  <div className={classNames(projectcss.all, sty.freeBox__rUV)}>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tSiZp)}
                    >
                      <TestimonialCard
                        className={classNames(
                          "__wab_instance",
                          sty.testimonialCard__hFy3S
                        )}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5BahR)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zeTt)}
                    >
                      <TestimonialCard
                        className={classNames(
                          "__wab_instance",
                          sty.testimonialCard__cmjK
                        )}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__awghu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bKyUb)}
                    >
                      <TestimonialCard
                        className={classNames(
                          "__wab_instance",
                          sty.testimonialCard__wkcHc
                        )}
                      />
                    </div>
                  </div>
                </SliderWrapper>
              );
            })()}
          </section>
          <section className={classNames(projectcss.all, sty.section__tgQ3B)}>
            <div className={classNames(projectcss.all, sty.freeBox__xXuJf)}>
              <h6
                className={classNames(
                  projectcss.all,
                  projectcss.h6,
                  projectcss.__wab_text,
                  sty.h6__ehpXk
                )}
              >
                {"Our Promise"}
              </h6>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__h0B2G
                )}
              >
                {"continuous coaching improvement"}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__fUyyp)}>
              <div className={classNames(projectcss.all, sty.freeBox__rM2Pl)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___6RMI)}
                  displayHeight={"100px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/hockey_lab_website/images/fihLogoSvg.svg",
                    fullWidth: 291.02,
                    fullHeight: 151.18,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__tJtXv)}>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__w3B
                    )}
                  >
                    {"Level 4 Coach"}
                  </h4>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__yoZtU
                    )}
                  >
                    {"Coach Educator"}
                  </h4>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___0UaT7)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__dv7DC)}
                  displayHeight={"100px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/hockey_lab_website/images/ahfLogoSvg.svg",
                    fullWidth: 264.45,
                    fullHeight: 52.492,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__dwqQp)}>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__mVXmM
                    )}
                  >
                    {"High Performance GK"}
                  </h4>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__sizT4)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__qzkf9)}
                  displayHeight={"100px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/hockey_lab_website/images/stJohnLogoSvg.svg",
                    fullWidth: 86,
                    fullHeight: 70,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__gPqnq)}>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__eTi62
                    )}
                  >
                    {"First Aid Certified"}
                  </h4>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__xKbHc)}>
            <div className={classNames(projectcss.all, sty.freeBox__tGeLo)}>
              <h6
                className={classNames(
                  projectcss.all,
                  projectcss.h6,
                  projectcss.__wab_text,
                  sty.h6__sjGt4
                )}
              >
                {"Trusted by"}
              </h6>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__dz4P
                )}
              >
                {"Our Partners"}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__xkUVz)}>
              <div className={classNames(projectcss.all, sty.freeBox__x7Fx6)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__hEodd)}
                  displayHeight={"100px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/hockey_lab_website/images/gshaSvg.svg",
                    fullWidth: 755.91,
                    fullHeight: 188.98,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___2TjVc)}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__vrbHp
                    )}
                  >
                    {"Gongshu Hockey Association\nTechnical Director"}
                  </h4>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__ur9Hq)}>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__qfa37
              )}
            >
              {"WE BELIEVE IN INDIVIDUALS"}
            </h2>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ua0I
              )}
            >
              {
                "At Hockey Lab, we are dedicated in inspiring individuals to experience the joy of field hockey. Our expert coaching team, led by a qualified FIH Educator with extensive first-hand international experience, combines their deep understanding of the game with proven strategies to deliver exceptional programs tailored to all skill levels."
              }
            </div>
          </section>
          <div className={classNames(projectcss.all, sty.freeBox__gDk8)}>
            <div className={classNames(projectcss.all, sty.freeBox__sZzFk)}>
              <div className={classNames(projectcss.all, sty.freeBox___91XyG)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__eo2P
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__m2KVz)}
                    displayHeight={"40px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"110px"}
                    src={{
                      src: "/plasmic/hockey_lab_website/images/logoHorizontalMonoWhiteSvg.svg",
                      fullWidth: 329.47,
                      fullHeight: 117.12,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
                <div className={classNames(projectcss.all, sty.freeBox__tFmfc)}>
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__c4Lu0
                    )}
                  >
                    {"Connect with us"}
                  </h6>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ooX7R)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__fpTtx
                      )}
                      component={Link}
                      href={"https://www.instagram.com/hockeylabhk"}
                      platform={"nextjs"}
                    >
                      <InstagramSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__zHRkD)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__pz8Ud
                      )}
                      component={Link}
                      href={"https://www.facebook.com/hockeylabhk"}
                      platform={"nextjs"}
                    >
                      <FacebookSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__mH4WC)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__e5D5M
                      )}
                      component={Link}
                      href={"mailto:info@hockeylabhk.com"}
                      platform={"nextjs"}
                    >
                      <EmailSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__nTgYs)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__iO32B)}>
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6__kYHd9
                  )}
                >
                  {"Company"}
                </h6>
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6__qrjeh
                  )}
                >
                  {"Hockey Lab Limited"}
                </h6>
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6__h0Jst
                  )}
                >
                  {"2F Le Diamant\n703-705 Nathan Road\nMong Kok"}
                </h6>
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6___9NJae
                  )}
                >
                  {"info@hockeylabhk.com"}
                </h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerNavBar",
    "h1",
    "blockquote",
    "columns",
    "sliderCarousel"
  ],
  headerNavBar: ["headerNavBar"],
  h1: ["h1"],
  blockquote: ["blockquote"],
  columns: ["columns"],
  sliderCarousel: ["sliderCarousel"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerNavBar: typeof HeaderNavBar;
  h1: "h1";
  blockquote: "blockquote";
  columns: "div";
  sliderCarousel: typeof SliderWrapper;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerNavBar: makeNodeComponent("headerNavBar"),
    h1: makeNodeComponent("h1"),
    blockquote: makeNodeComponent("blockquote"),
    columns: makeNodeComponent("columns"),
    sliderCarousel: makeNodeComponent("sliderCarousel"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
