/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vqq2EkAzn3CTTzmF7cN3ao
// Component: Qey7pJzlldRh

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: vqq2EkAzn3CTTzmF7cN3ao/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vqq2EkAzn3CTTzmF7cN3ao/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: vqq2EkAzn3CTTzmF7cN3ao/projectcss
import sty from "./PlasmicTestimonialCard.module.css"; // plasmic-import: Qey7pJzlldRh/css

import FormatQuoteSvgrepoComSvgIcon from "./icons/PlasmicIcon__FormatQuoteSvgrepoComSvg"; // plasmic-import: 189YLvEKZ9fA/icon

createPlasmicElementProxy;

export type PlasmicTestimonialCard__VariantMembers = {};
export type PlasmicTestimonialCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestimonialCard__VariantsArgs;
export const PlasmicTestimonialCard__VariantProps =
  new Array<VariantPropType>();

export type PlasmicTestimonialCard__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicTestimonialCard__ArgsType;
export const PlasmicTestimonialCard__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2"
);

export type PlasmicTestimonialCard__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
  h4?: Flex__<"h4">;
  h6?: Flex__<"h6">;
};

export interface DefaultTestimonialCardProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTestimonialCard__RenderFunc(props: {
  variants: PlasmicTestimonialCard__VariantsArgs;
  args: PlasmicTestimonialCard__ArgsType;
  overrides: PlasmicTestimonialCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox___69Uu9)}>
        <div className={classNames(projectcss.all, sty.freeBox__vgooN)}>
          <FormatQuoteSvgrepoComSvgIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg)}
            role={"img"}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__bdnOa)}>
          <h4
            data-plasmic-name={"h4"}
            data-plasmic-override={overrides.h4}
            className={classNames(projectcss.all, projectcss.h4, sty.h4)}
          >
            {renderPlasmicSlot({
              defaultContents: "Arshmit Pannu",
              value: args.children
            })}
          </h4>
          <h6
            data-plasmic-name={"h6"}
            data-plasmic-override={overrides.h6}
            className={classNames(projectcss.all, projectcss.h6, sty.h6)}
          >
            {renderPlasmicSlot({
              defaultContents:
                "Canadian Junior Hockey World Cup Representative",
              value: args.slot
            })}
          </h6>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__ebp0W)}>
        {renderPlasmicSlot({
          defaultContents:
            "Jackie has been an influential figure in my sporting career, and I\u2019m incredibly grateful for the impact he\u2019s had on me both on and off the field. I first met him at 13, fresh out of mini-hockey with nothing but raw talent. Jackie was the one who introduced me to the realities of adult hockey. Week after week, he worked with me to sharpen my ball skills, positioning, tactical knowledge, game management, and overall understanding of the modern game.\n\nWhat makes Jackie stand out is the way he could shape every session to what we needed most, while still letting us focus on areas we wanted to grow. His structured training, clear goals, and video sessions mirrored the professionalism I later saw at the international level. Beyond technical skills, Jackie also taught me what it means to be a leader, how to communicate, motivate teammates, and carry myself with accountability.\n\nHis commitment to my growth led me to my debut for Khalsa A at 16. Years later, one of my proudest moments came when I wore Team Canada\u2019s colours at the 2023 Junior World Cup in Malaysia. Having Jackie travel all the way there to sit in the stands and watch me play was incredibly special. It felt like everything we worked on together had come full circle, and it turned that tournament into a shared accomplishment.\n\nTo me, Jackie is far more than a coach. He\u2019s a mentor, role model, and friend who not only shaped me as a player, but also as a leader and person. His influence will stay with me for life.",
          value: args.slot2
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "h4", "h6"],
  svg: ["svg"],
  h4: ["h4"],
  h6: ["h6"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  h4: "h4";
  h6: "h6";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestimonialCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestimonialCard__VariantsArgs;
    args?: PlasmicTestimonialCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTestimonialCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTestimonialCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTestimonialCard__ArgProps,
          internalVariantPropNames: PlasmicTestimonialCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTestimonialCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestimonialCard";
  } else {
    func.displayName = `PlasmicTestimonialCard.${nodeName}`;
  }
  return func;
}

export const PlasmicTestimonialCard = Object.assign(
  // Top-level PlasmicTestimonialCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    h4: makeNodeComponent("h4"),
    h6: makeNodeComponent("h6"),

    // Metadata about props expected for PlasmicTestimonialCard
    internalVariantProps: PlasmicTestimonialCard__VariantProps,
    internalArgProps: PlasmicTestimonialCard__ArgProps
  }
);

export default PlasmicTestimonialCard;
/* prettier-ignore-end */
